language: node_js
node_js:
- '5'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GH_REF: github.com/jupyterlab/extension-builder.git
  - secure: JYVFtP5MNSTXr7/zyln8QJn0pa57cFzQy0gNtHqjRuHIR844F7Ot8JG5m0P68sNGpyWXcsio1dbPgy3/BcF9XK1FiEO/OsCVcOcDoVITvcnKccmdBIR5FEvaDb8VINFQNU1fCe6x5G3JEVxU9ZvIdXBe+jbllgPufogdWELjUuowO7TnW0URSfBf1Vkgwrg0WWlnY0QfRKFG82IxmSgkdPyZY4WjMeyJOfrEUeascTBKVIy75VCxn/82Ir4JMv9S7RaQuAPNJqnfnWPoEjF1eXCVFM9jRjjrux9eQvFIK62m350ufBpF6JhfMGHtAma8cc8mCAdVM+h+FrGxbkdE1HKANDca0CTmfa/uHrGwyIbdQ3MgVWpVXzUo22f0XJNR8BL70I2/RJ/CXnmDClIyG1qTF1xM3AbTWqTFLpvTdv84rMX9thqp2iqw/AHLsWRQWDxGZNgAhWO7iKbJot+sI1Y1uFoeAlrnMwmJRZIMT2GXuExlHmN8ZiH/Go5MvVgPdGn4eeun1xurVm/7YEl825M30Xjzq6bOOCyyrTP/EO2rGfpe/lOwv+rqoDuDAV8hOxdYcMeXKhzagh0WAOfhZannxq6KsPBNisHuLrcc5ua/PXlgMjUZ2h9YYweTjhyxGnZo1pf/1VGhtC46qeAglkE7k91Thch0HkmQZ2ioZqk=
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh
# after_success:
# - bash ./scripts/travis_after_success.sh
